Document: openvas-smb
Title: Debian openvas-smb Manual
Author: <insert document author here>
Abstract: This manual describes what openvas-smb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openvas-smb/openvas-smb.sgml.gz

Format: postscript
Files: /usr/share/doc/openvas-smb/openvas-smb.ps.gz

Format: text
Files: /usr/share/doc/openvas-smb/openvas-smb.text.gz

Format: HTML
Index: /usr/share/doc/openvas-smb/html/index.html
Files: /usr/share/doc/openvas-smb/html/*.html
